name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@v4

    - name: Extract Project
      run: unzip *.zip -d project_code

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Compile and Build APK
      run: |
        cd project_code
        cd $(dirname $(find . -name "gradlew" | head -n 1))
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Save APK
      uses: actions/upload-artifact@v4
      with:
        name: Chess-Multiplayer-App
        path: project_code/**/app/build/outputs/apk/debug/*.apk
        
